services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shipmater
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - shipmater_db:/var/lib/postgresql/data

volumes:
  shipmater_db:
